#!/usr/bin/env python3

"""
Analyze Monte Carlo standard error (MCSE) of Bayesian Regional LoRA posterior
mean estimation.

This script analyzes posterior realizations previously generated by
``audit_br_lora_posterior.py``. No model loading or inference is performed.

For independent posterior realizations, the pixelwise Monte Carlo standard
error of the estimated posterior mean is computed as

    sample_posterior_std / sqrt(number_of_realizations).

MCSE is summarized inside the prescribed lesion mask. No reliability score or
image-quality interpretation is assigned here.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
import sys

# Keep NumPy before Torch on macOS.
import numpy as np
import torch


SAMPLE_COUNTS = (
    5,
    10,
    20,
    30,
    50,
    75,
    100,
    150,
    200,
)

REQUIRED_KEYS = (
    "prediction_samples",
    "composite_samples",
    "transferred_masks",
    "posterior_samples",
)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description=(
            "Analyze Monte Carlo standard error of BR-LoRA posterior "
            "mean estimates."
        )
    )

    parser.add_argument(
        "--posterior-file",
        type=Path,
        required=True,
        help=(
            "posterior_realizations.pt produced by "
            "audit_br_lora_posterior.py"
        ),
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(
            "outputs/br_lora_posterior/mcse"
        ),
        help=(
            "Directory for MCSE analysis outputs."
        ),
    )

    return parser.parse_args()


def load_posterior_payload(
    path: Path,
) -> dict:
    """Load one trusted BR-LoRA posterior realization artifact."""

    resolved = (
        path
        .expanduser()
        .resolve()
    )

    if not resolved.is_file():
        raise FileNotFoundError(
            f"Posterior realization file not found:\n{resolved}"
        )

    payload = torch.load(
        resolved,
        map_location="cpu",
        weights_only=False,
    )

    if not isinstance(
        payload,
        dict,
    ):
        raise RuntimeError(
            "Posterior artifact must contain a dictionary."
        )

    missing = [
        key
        for key in REQUIRED_KEYS
        if key not in payload
    ]

    if missing:
        raise RuntimeError(
            "Posterior artifact is missing required entries:\n"
            + "\n".join(
                missing
            )
        )

    return payload


def validate_payload(
    payload: dict,
) -> None:
    """Validate tensors required for MCSE analysis."""

    prediction_samples = payload[
        "prediction_samples"
    ]

    composite_samples = payload[
        "composite_samples"
    ]

    masks = payload[
        "transferred_masks"
    ]

    posterior_samples = int(
        payload[
            "posterior_samples"
        ]
    )

    if prediction_samples.ndim != 5:
        raise RuntimeError(
            "prediction_samples must have shape "
            "(samples, batch, channel, height, width)."
        )

    if composite_samples.shape != prediction_samples.shape:
        raise RuntimeError(
            "Prediction and composite realization stacks must have "
            "identical shapes."
        )

    if masks.ndim != 4:
        raise RuntimeError(
            "transferred_masks must have shape "
            "(batch, channel, height, width)."
        )

    if prediction_samples.shape[1:] != masks.shape:
        raise RuntimeError(
            "Posterior samples and transferred masks have "
            "inconsistent shapes."
        )

    if prediction_samples.shape[0] != posterior_samples:
        raise RuntimeError(
            "Serialized posterior sample count does not match "
            "the realization stack."
        )

    if posterior_samples < max(
        SAMPLE_COUNTS
    ):
        raise RuntimeError(
            "Posterior artifact does not contain enough realizations "
            "for the requested MCSE sample counts."
        )

    for name, tensor in (
        (
            "prediction_samples",
            prediction_samples,
        ),
        (
            "composite_samples",
            composite_samples,
        ),
        (
            "transferred_masks",
            masks,
        ),
    ):
        if not torch.isfinite(
            tensor
        ).all():
            raise RuntimeError(
                f"{name} contains non-finite values."
            )

    if not (
        masks
        > 0
    ).any():
        raise RuntimeError(
            "Transferred masks contain no positive pixels."
        )


def compute_pixelwise_mcse(
    samples: torch.Tensor,
    *,
    sample_count: int,
) -> torch.Tensor:
    """
    Compute pixelwise MCSE of the posterior-mean estimator.

    The standard deviation uses the ordinary sample convention
    (Bessel correction, correction=1).
    """

    if (
        isinstance(
            sample_count,
            bool,
        )
        or not isinstance(
            sample_count,
            int,
        )
        or sample_count < 2
    ):
        raise ValueError(
            "sample_count must be an integer >= 2."
        )

    if samples.ndim != 5:
        raise RuntimeError(
            "samples must have shape "
            "(samples, batch, channel, height, width)."
        )

    if sample_count > samples.shape[0]:
        raise RuntimeError(
            "sample_count exceeds the available posterior realizations."
        )

    prefix = samples[
        :sample_count
    ]

    sample_std = prefix.std(
        dim=0,
        correction=1,
    )

    mcse = (
        sample_std
        / np.sqrt(
            sample_count
        )
    )

    if not torch.isfinite(
        mcse
    ).all():
        raise RuntimeError(
            "Computed MCSE contains non-finite values."
        )

    if (
        mcse
        < 0
    ).any():
        raise RuntimeError(
            "Computed MCSE contains negative values."
        )

    return mcse




def summarize_masked_mcse(
    *,
    samples: torch.Tensor,
    masks: torch.Tensor,
) -> list[dict[str, float]]:
    """
    Summarize pixelwise MCSE inside the prescribed lesion mask.

    The returned rows correspond to ``SAMPLE_COUNTS``. Masked pixels from all
    audit cases are pooled for this initial methodological analysis.
    """

    if not isinstance(
        samples,
        torch.Tensor,
    ):
        raise TypeError(
            "`samples` must be a torch.Tensor."
        )

    if not isinstance(
        masks,
        torch.Tensor,
    ):
        raise TypeError(
            "`masks` must be a torch.Tensor."
        )

    if masks.ndim != 4:
        raise RuntimeError(
            "`masks` must have shape "
            "(batch, channel, height, width)."
        )

    if samples.shape[1:] != masks.shape:
        raise RuntimeError(
            "Posterior samples and masks have inconsistent shapes."
        )

    selected = (
        masks
        > 0
    )

    selected_count = int(
        selected.sum().item()
    )

    if selected_count <= 0:
        raise RuntimeError(
            "The transferred masks select zero pixels."
        )

    rows: list[
        dict[str, float]
    ] = []

    for sample_count in SAMPLE_COUNTS:

        mcse = compute_pixelwise_mcse(
            samples,
            sample_count=sample_count,
        )

        masked_mcse = mcse[
            selected
        ]

        if masked_mcse.numel() != selected_count:
            raise RuntimeError(
                "Masked MCSE pixel count is inconsistent."
            )

        if not torch.isfinite(
            masked_mcse
        ).all():
            raise RuntimeError(
                "Masked MCSE contains non-finite values."
            )

        rows.append(
            {
                "samples": sample_count,
                "mean_mcse": float(
                    masked_mcse.mean()
                ),
                "median_mcse": float(
                    masked_mcse.median()
                ),
                "p95_mcse": float(
                    torch.quantile(
                        masked_mcse,
                        0.95,
                    )
                ),
                "max_mcse": float(
                    masked_mcse.max()
                ),
            }
        )

    return rows


def save_mcse_summary_csv(
    *,
    prediction_summary: list[dict[str, float]],
    composite_summary: list[dict[str, float]],
    path: Path,
) -> None:
    """Save prediction/composite lesion-region MCSE summaries."""

    if len(
        prediction_summary
    ) != len(
        composite_summary
    ):
        raise RuntimeError(
            "Prediction and composite MCSE summaries have "
            "different lengths."
        )

    rows = []

    for prediction_row, composite_row in zip(
        prediction_summary,
        composite_summary,
    ):

        if (
            prediction_row[
                "samples"
            ]
            != composite_row[
                "samples"
            ]
        ):
            raise RuntimeError(
                "Prediction and composite MCSE summaries have "
                "different sample counts."
            )

        rows.append(
            {
                "samples": prediction_row[
                    "samples"
                ],
                "prediction_mean_mcse": prediction_row[
                    "mean_mcse"
                ],
                "prediction_median_mcse": prediction_row[
                    "median_mcse"
                ],
                "prediction_p95_mcse": prediction_row[
                    "p95_mcse"
                ],
                "prediction_max_mcse": prediction_row[
                    "max_mcse"
                ],
                "composite_mean_mcse": composite_row[
                    "mean_mcse"
                ],
                "composite_median_mcse": composite_row[
                    "median_mcse"
                ],
                "composite_p95_mcse": composite_row[
                    "p95_mcse"
                ],
                "composite_max_mcse": composite_row[
                    "max_mcse"
                ],
            }
        )

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with path.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as file:

        writer = csv.DictWriter(
            file,
            fieldnames=rows[
                0
            ].keys(),
        )

        writer.writeheader()
        writer.writerows(
            rows
        )


def main() -> None:
    """Load and validate the posterior artifact."""

    args = parse_args()

    payload = load_posterior_payload(
        args.posterior_file
    )

    validate_payload(
        payload
    )

    prediction_samples = payload[
        "prediction_samples"
    ]

    composite_samples = payload[
        "composite_samples"
    ]

    transferred_masks = payload[
        "transferred_masks"
    ]

    prediction_summary = summarize_masked_mcse(
        samples=prediction_samples,
        masks=transferred_masks,
    )

    composite_summary = summarize_masked_mcse(
        samples=composite_samples,
        masks=transferred_masks,
    )

    for prediction_row, composite_row in zip(
        prediction_summary,
        composite_summary,
    ):
        for metric in (
            "mean_mcse",
            "median_mcse",
            "p95_mcse",
            "max_mcse",
        ):
            if not np.isclose(
                prediction_row[
                    metric
                ],
                composite_row[
                    metric
                ],
                rtol=1.0e-6,
                atol=1.0e-12,
            ):
                raise RuntimeError(
                    "Prediction and composite inside-mask MCSE "
                    f"differ for {metric} at "
                    f"N={prediction_row['samples']}."
                )

    output_dir = (
        args.output_dir
        .expanduser()
        .resolve()
    )

    csv_path = (
        output_dir
        / "posterior_mcse_summary.csv"
    )

    save_mcse_summary_csv(
        prediction_summary=prediction_summary,
        composite_summary=composite_summary,
        path=csv_path,
    )

    print()
    print(
        "=" * 78
    )
    print(
        "BR-LoRA POSTERIOR MCSE ANALYSIS"
    )
    print(
        "=" * 78
    )

    print(
        "Posterior realizations        :",
        payload[
            "posterior_samples"
        ],
    )

    print(
        "Prediction shape              :",
        tuple(
            prediction_samples.shape
        ),
    )

    print()
    print(
        "Inside-mask MCSE by posterior sample count"
    )
    print(
        "-" * 78
    )

    print(
        f"{'Samples':>8} "
        f"{'Mean':>14} "
        f"{'Median':>14} "
        f"{'P95':>14} "
        f"{'Maximum':>14}"
    )

    for row in prediction_summary:
        print(
            f"{int(row['samples']):>8d} "
            f"{row['mean_mcse']:>14.8e} "
            f"{row['median_mcse']:>14.8e} "
            f"{row['p95_mcse']:>14.8e} "
            f"{row['max_mcse']:>14.8e}"
        )

    print()
    print(
        "Prediction/composite agreement: PASS"
    )

    print(
        "Summary CSV                    :",
        csv_path,
    )

    print()
    print(
        "MCSE ANALYSIS: PASS"
    )
    print(
        "=" * 78
    )


if __name__ == "__main__":
    try:
        main()

    except (
        FileNotFoundError,
        RuntimeError,
        TypeError,
        ValueError,
    ) as exc:
        print(
            "\nBR-LoRA POSTERIOR MCSE ANALYSIS FAILED",
            file=sys.stderr,
        )

        print(
            exc,
            file=sys.stderr,
        )

        sys.exit(
            1
        )