#!/usr/bin/env python3

"""
Analyze Monte Carlo convergence of Bayesian Regional LoRA posterior sampling.

This script analyzes posterior realizations previously generated by
``audit_br_lora_posterior.py``. No model loading or inference is performed.

Given one serialized posterior realization stack, the script evaluates how
Monte Carlo estimates stabilize as the number of posterior realizations
increases. The first 200 posterior realizations define the higher-sample Monte
Carlo reference used for comparison.

No uncertainty interpretation or reliability scoring is performed here.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
import sys

import matplotlib.pyplot as plt
import torch

REFERENCE_SAMPLE_COUNT = 200

SAMPLE_COUNTS = (
    5,
    10,
    20,
    30,
    50,
    75,
    100,
    150,
    200,
)

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Analyze Monte Carlo convergence of BR-LoRA posterior "
            "realizations."
        )
    )

    parser.add_argument(
        "--posterior-file",
        type=Path,
        required=True,
        help=(
            "posterior_realizations.pt produced by "
            "audit_br_lora_posterior.py"
        ),
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(
            "outputs/br_lora_posterior/convergence"
        ),
        help=(
            "Directory for convergence summaries."
        ),
    )

    return parser.parse_args()

def load_posterior_payload(
    path: Path,
) -> dict:
    """
    Load a trusted BR-LoRA posterior realization artifact.
    """

    resolved = (
        path
        .expanduser()
        .resolve()
    )

    if not resolved.is_file():
        raise FileNotFoundError(
            f"Posterior realization file not found:\n{resolved}"
        )

    payload = torch.load(
        resolved,
        map_location="cpu",
        weights_only=False,
    )

    if not isinstance(
        payload,
        dict,
    ):
        raise RuntimeError(
            "Posterior artifact must contain a dictionary."
        )

    return payload

REQUIRED_KEYS = (
    "prediction_samples",
    "composite_samples",
    "transferred_masks",
    "posterior_samples",
)

def validate_payload(
    payload: dict,
) -> None:
    """
    Validate the serialized posterior realization artifact.
    """

    missing = [
        key
        for key in REQUIRED_KEYS
        if key not in payload
    ]

    if missing:
        raise RuntimeError(
            "Posterior artifact is missing required entries:\n"
            + "\n".join(missing)
        )
    
def validate_tensor_shapes(
    payload: dict,
) -> None:
    """
    Validate tensor dimensions stored in the posterior realization artifact.
    """

    prediction_samples = payload[
        "prediction_samples"
    ]

    composite_samples = payload[
        "composite_samples"
    ]

    transferred_masks = payload[
        "transferred_masks"
    ]

    posterior_samples = int(
        payload[
            "posterior_samples"
        ]
    )

    if prediction_samples.ndim != 5:
        raise RuntimeError(
            "prediction_samples must have shape "
            "(samples, batch, channel, height, width)."
        )

    if composite_samples.ndim != 5:
        raise RuntimeError(
            "composite_samples must have shape "
            "(samples, batch, channel, height, width)."
        )

    if transferred_masks.ndim != 4:
        raise RuntimeError(
            "transferred_masks must have shape "
            "(batch, channel, height, width)."
        )

    if prediction_samples.shape != composite_samples.shape:
        raise RuntimeError(
            "Prediction and composite sample stacks "
            "must have identical shapes."
        )

    if prediction_samples.shape[0] != posterior_samples:
        raise RuntimeError(
            "Serialized posterior sample count does "
            "not match the tensor leading dimension."
        )

    if prediction_samples.shape[1:] != (
        transferred_masks.shape
    ):
        raise RuntimeError(
            "Prediction tensors and transferred masks "
            "have inconsistent spatial dimensions."
        )

    if posterior_samples < REFERENCE_SAMPLE_COUNT:
        raise RuntimeError(
            "The artifact contains fewer posterior "
            "realizations than the requested reference "
            "sample count."
        )

def running_posterior_mean(
    samples: torch.Tensor,
) -> torch.Tensor:
    """
    Compute cumulative Monte Carlo posterior means.

    Parameters
    ----------
    samples
        Posterior realization stack with shape
        ``(samples, batch, channel, height, width)``.

    Returns
    -------
    torch.Tensor
        Running posterior means with the same shape as ``samples``.
        Entry ``k`` equals ``samples[:k + 1].mean(dim=0)``.
    """

    if not isinstance(
        samples,
        torch.Tensor,
    ):
        raise TypeError(
            "`samples` must be a torch.Tensor."
        )

    if samples.ndim != 5:
        raise RuntimeError(
            "`samples` must have shape "
            "(samples, batch, channel, height, width)."
        )

    if samples.shape[0] <= 0:
        raise RuntimeError(
            "`samples` must contain at least one posterior realization."
        )

    if not torch.is_floating_point(
        samples
    ):
        raise TypeError(
            "`samples` must use a floating-point dtype."
        )

    if not torch.isfinite(
        samples
    ).all():
        raise RuntimeError(
            "`samples` contains non-finite values."
        )

    cumulative = torch.cumsum(
        samples,
        dim=0,
    )

    counts = torch.arange(
        1,
        samples.shape[0] + 1,
        dtype=samples.dtype,
        device=samples.device,
    ).view(
        -1,
        1,
        1,
        1,
        1,
    )

    running_mean = (
        cumulative
        / counts
    )

    if running_mean.shape != samples.shape:
        raise RuntimeError(
            "Running posterior mean has an unexpected shape."
        )

    if not torch.isfinite(
        running_mean
    ).all():
        raise RuntimeError(
            "Running posterior mean contains non-finite values."
        )

    return running_mean

def running_posterior_variance(
    samples: torch.Tensor,
) -> torch.Tensor:
    """
    Compute cumulative Monte Carlo posterior variances.

    Population variance (correction=0) is used so this matches the
    posterior-variance convention used by the validated BR-LoRA inference
    implementation.

    Entry ``k`` equals the variance of ``samples[:k + 1]``.
    """

    if not isinstance(
        samples,
        torch.Tensor,
    ):
        raise TypeError(
            "`samples` must be a torch.Tensor."
        )

    if samples.ndim != 5:
        raise RuntimeError(
            "`samples` must have shape "
            "(samples, batch, channel, height, width)."
        )

    if samples.shape[0] <= 0:
        raise RuntimeError(
            "`samples` must contain at least one posterior realization."
        )

    if not torch.is_floating_point(
        samples
    ):
        raise TypeError(
            "`samples` must use a floating-point dtype."
        )

    if not torch.isfinite(
        samples
    ).all():
        raise RuntimeError(
            "`samples` contains non-finite values."
        )

    running_mean = torch.zeros_like(
        samples[
            0
        ]
    )

    running_m2 = torch.zeros_like(
        samples[
            0
        ]
    )

    variances = []

    for sample_count, sample in enumerate(
        samples,
        start=1,
    ):
        delta = (
            sample
            - running_mean
        )

        running_mean = (
            running_mean
            + delta
            / sample_count
        )

        delta_after_update = (
            sample
            - running_mean
        )

        running_m2 = (
            running_m2
            + delta
            * delta_after_update
        )

        variance = (
            running_m2
            / sample_count
        )

        variance = torch.clamp(
            variance,
            min=0.0,
        )

        variances.append(
            variance
        )

    running_variance = torch.stack(
        variances,
        dim=0,
    )

    if running_variance.shape != samples.shape:
        raise RuntimeError(
            "Running posterior variance has an unexpected shape."
        )

    if not torch.isfinite(
        running_variance
    ).all():
        raise RuntimeError(
            "Running posterior variance contains non-finite values."
        )

    if (
        running_variance
        < 0
    ).any():
        raise RuntimeError(
            "Running posterior variance contains negative values."
        )

    return running_variance


def compute_running_error_to_reference(
    running_mean: torch.Tensor,
    reference_mean: torch.Tensor,
    mask: torch.Tensor | None = None,
) -> dict[
    str,
    torch.Tensor,
]:
    """
    Compare every running posterior mean against the final reference mean.

    When ``mask`` is omitted, errors are computed over every batch, channel,
    and spatial location.

    When ``mask`` is provided, errors are computed only over pixels for which
    the mask is positive. The mask must have shape
    ``(batch, channel, height, width)``.

    One scalar error is returned per Monte Carlo sample count.
    """

    if running_mean.ndim != 5:
        raise RuntimeError(
            "`running_mean` must have shape "
            "(samples, batch, channel, height, width)."
        )

    if reference_mean.ndim != 4:
        raise RuntimeError(
            "`reference_mean` must have shape "
            "(batch, channel, height, width)."
        )

    if running_mean.shape[1:] != reference_mean.shape:
        raise RuntimeError(
            "Running and reference means have inconsistent shapes."
        )

    difference = (
        running_mean
        - reference_mean.unsqueeze(
            0
        )
    )

    if mask is None:

        absolute_difference = (
            difference.abs()
        )

        mae = absolute_difference.mean(
            dim=(
                1,
                2,
                3,
                4,
            )
        )

        rmse = torch.sqrt(
            difference.square().mean(
                dim=(
                    1,
                    2,
                    3,
                    4,
                )
            )
        )

        max_abs = absolute_difference.amax(
            dim=(
                1,
                2,
                3,
                4,
            )
        )

    else:

        if not isinstance(
            mask,
            torch.Tensor,
        ):
            raise TypeError(
                "`mask` must be a torch.Tensor or None."
            )

        if mask.ndim != 4:
            raise RuntimeError(
                "`mask` must have shape "
                "(batch, channel, height, width)."
            )

        if mask.shape != reference_mean.shape:
            raise RuntimeError(
                "`mask` and reference mean must have identical shapes."
            )

        if not torch.isfinite(
            mask
        ).all():
            raise RuntimeError(
                "`mask` contains non-finite values."
            )

        selected = (
            mask
            > 0
        )

        selected_count = int(
            selected.sum().item()
        )

        if selected_count <= 0:
            raise RuntimeError(
                "`mask` selects zero pixels."
            )

        selected = (
            selected.unsqueeze(
                0
            )
            .expand_as(
                difference
            )
        )

        selected_difference = (
            difference[
                selected
            ]
            .reshape(
                difference.shape[
                    0
                ],
                -1,
            )
        )

        absolute_difference = (
            selected_difference.abs()
        )

        mae = absolute_difference.mean(
            dim=1
        )

        rmse = torch.sqrt(
            selected_difference.square().mean(
                dim=1
            )
        )

        max_abs = absolute_difference.amax(
            dim=1
        )

    for name, values in (
        (
            "mae",
            mae,
        ),
        (
            "rmse",
            rmse,
        ),
        (
            "max_abs",
            max_abs,
        ),
    ):
        if not torch.isfinite(
            values
        ).all():
            raise RuntimeError(
                f"Computed {name} contains non-finite values."
            )

    return {
        "mae": mae,
        "rmse": rmse,
        "max_abs": max_abs,
    }

def summarize_sample_counts(
    *,
    prediction_errors: dict[str, torch.Tensor],
    composite_errors: dict[str, torch.Tensor],
    prediction_inside_errors: dict[str, torch.Tensor],
    composite_inside_errors: dict[str, torch.Tensor],
    prediction_variance_errors: dict[str, torch.Tensor],
    composite_variance_errors: dict[str, torch.Tensor],
    prediction_variance_inside_errors: dict[str, torch.Tensor],
    composite_variance_inside_errors: dict[str, torch.Tensor],
) -> list[dict[str, float]]:
    """
    Extract posterior-mean and posterior-variance convergence metrics at the
    predefined Monte Carlo sample counts.
    """

    summary = []

    for count in SAMPLE_COUNTS:

        index = count - 1

        summary.append(
            {
                "samples": count,

                "prediction_mae": float(
                    prediction_errors["mae"][index]
                ),
                "prediction_rmse": float(
                    prediction_errors["rmse"][index]
                ),
                "prediction_max_abs": float(
                    prediction_errors["max_abs"][index]
                ),

                "composite_mae": float(
                    composite_errors["mae"][index]
                ),
                "composite_rmse": float(
                    composite_errors["rmse"][index]
                ),
                "composite_max_abs": float(
                    composite_errors["max_abs"][index]
                ),

                "prediction_inside_mae": float(
                    prediction_inside_errors["mae"][index]
                ),
                "prediction_inside_rmse": float(
                    prediction_inside_errors["rmse"][index]
                ),
                "prediction_inside_max_abs": float(
                    prediction_inside_errors["max_abs"][index]
                ),

                "composite_inside_mae": float(
                    composite_inside_errors["mae"][index]
                ),
                "composite_inside_rmse": float(
                    composite_inside_errors["rmse"][index]
                ),
                "composite_inside_max_abs": float(
                    composite_inside_errors["max_abs"][index]
                ),

                "prediction_variance_mae": float(
                    prediction_variance_errors["mae"][index]
                ),
                "prediction_variance_rmse": float(
                    prediction_variance_errors["rmse"][index]
                ),
                "prediction_variance_max_abs": float(
                    prediction_variance_errors["max_abs"][index]
                ),

                "composite_variance_mae": float(
                    composite_variance_errors["mae"][index]
                ),
                "composite_variance_rmse": float(
                    composite_variance_errors["rmse"][index]
                ),
                "composite_variance_max_abs": float(
                    composite_variance_errors["max_abs"][index]
                ),

                "prediction_variance_inside_mae": float(
                    prediction_variance_inside_errors["mae"][index]
                ),
                "prediction_variance_inside_rmse": float(
                    prediction_variance_inside_errors["rmse"][index]
                ),
                "prediction_variance_inside_max_abs": float(
                    prediction_variance_inside_errors["max_abs"][index]
                ),

                "composite_variance_inside_mae": float(
                    composite_variance_inside_errors["mae"][index]
                ),
                "composite_variance_inside_rmse": float(
                    composite_variance_inside_errors["rmse"][index]
                ),
                "composite_variance_inside_max_abs": float(
                    composite_variance_inside_errors["max_abs"][index]
                ),
            }
        )

    return summary

def save_summary_csv(
    summary: list[dict[str, float]],
    path: Path,
) -> None:
    """
    Save Monte Carlo convergence summaries.
    """

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with path.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as file:

        writer = csv.DictWriter(
            file,
            fieldnames=summary[0].keys(),
        )

        writer.writeheader()

        writer.writerows(summary)



def save_convergence_figure(
    *,
    summary: list[dict[str, float]],
    path: Path,
) -> None:
    """
    Plot lesion-region Monte Carlo convergence of the posterior mean and
    posterior variance relative to the reference Monte Carlo estimates.

    Prediction and composite convergence are identical inside the prescribed
    lesion mask by hard regional composition, so only one lesion-region curve
    is shown in each panel.
    """

    sample_counts = [
        row[
            "samples"
        ]
        for row in summary
    ]

    mean_rmse = [
        row[
            "prediction_inside_rmse"
        ]
        for row in summary
    ]

    variance_rmse = [
        row[
            "prediction_variance_inside_rmse"
        ]
        for row in summary
    ]

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fig, axes = plt.subplots(
        1,
        2,
        figsize=(
            11,
            4,
        ),
    )

    axes[
        0
    ].plot(
        sample_counts,
        mean_rmse,
        marker="o",
    )

    axes[
        0
    ].set_yscale(
        "log"
    )

    axes[
        0
    ].set_xlabel(
        "Posterior realizations"
    )

    axes[
        0
    ].set_ylabel(
        f"RMSE to {REFERENCE_SAMPLE_COUNT}-sample reference"
    )

    axes[
        0
    ].set_title(
        "A. Posterior mean"
    )

    axes[
        0
    ].grid(
        True,
        which="both",
        alpha=0.3,
    )

    axes[
        1
    ].plot(
        sample_counts,
        variance_rmse,
        marker="o",
    )

    axes[
        1
    ].set_yscale(
        "log"
    )

    axes[
        1
    ].set_xlabel(
        "Posterior realizations"
    )

    axes[
        1
    ].set_ylabel(
        f"RMSE to {REFERENCE_SAMPLE_COUNT}-sample reference"
    )

    axes[
        1
    ].set_title(
        "B. Posterior variance"
    )

    axes[
        1
    ].grid(
        True,
        which="both",
        alpha=0.3,
    )

    plt.tight_layout()

    plt.savefig(
        path,
        dpi=300,
        bbox_inches="tight",
    )

    plt.close(
        fig
    )



def main() -> None:

    args = parse_args()

    payload = load_posterior_payload(
        args.posterior_file
    )

    validate_payload(
        payload
    )

    validate_tensor_shapes(
        payload
    )

    prediction_samples = payload[
        "prediction_samples"
    ]

    composite_samples = payload[
        "composite_samples"
    ]

    transferred_masks = payload[
        "transferred_masks"
    ]

    prediction_running_mean = (
        running_posterior_mean(
            prediction_samples
        )
    )

    composite_running_mean = (
        running_posterior_mean(
            composite_samples
        )
    )

    prediction_direct_mean = (
        prediction_samples.mean(
            dim=0
        )
    )

    composite_direct_mean = (
        composite_samples.mean(
            dim=0
        )
    )

    prediction_running_variance = (
        running_posterior_variance(
            prediction_samples
        )
    )

    composite_running_variance = (
        running_posterior_variance(
            composite_samples
        )
    )

    prediction_direct_variance = (
        prediction_samples.var(
            dim=0,
            correction=0,
        )
    )

    composite_direct_variance = (
        composite_samples.var(
            dim=0,
            correction=0,
        )
    )

    if not torch.allclose(
        prediction_running_mean[
            -1
        ],
        prediction_direct_mean,
    ):
        raise RuntimeError(
            "Final running prediction mean does not match "
            "the direct Monte Carlo mean."
        )


    if not torch.allclose(
        prediction_running_variance[
            -1
        ],
        prediction_direct_variance,
        rtol=1.0e-4,
        atol=1.0e-10,
    ):
        raise RuntimeError(
            "Final running prediction variance does not match "
            "the direct Monte Carlo variance."
        )

    if not torch.allclose(
        composite_running_variance[
            -1
        ],
        composite_direct_variance,
        rtol=1.0e-4,
        atol=1.0e-10,
    ):
        raise RuntimeError(
            "Final running composite variance does not match "
            "the direct Monte Carlo variance."
        )

    prediction_errors = (
        compute_running_error_to_reference(
            prediction_running_mean,
            prediction_direct_mean,
        )
    )

    composite_errors = (
        compute_running_error_to_reference(
            composite_running_mean,
            composite_direct_mean,
        )
    )

    prediction_inside_errors = (
        compute_running_error_to_reference(
            prediction_running_mean,
            prediction_direct_mean,
            mask=transferred_masks,
        )
    )

    composite_inside_errors = (
        compute_running_error_to_reference(
            composite_running_mean,
            composite_direct_mean,
            mask=transferred_masks,
        )
    )

    prediction_variance_errors = (
        compute_running_error_to_reference(
            prediction_running_variance,
            prediction_direct_variance,
        )
    )

    composite_variance_errors = (
        compute_running_error_to_reference(
            composite_running_variance,
            composite_direct_variance,
        )
    )

    prediction_variance_inside_errors = (
        compute_running_error_to_reference(
            prediction_running_variance,
            prediction_direct_variance,
            mask=transferred_masks,
        )
    )

    composite_variance_inside_errors = (
        compute_running_error_to_reference(
            composite_running_variance,
            composite_direct_variance,
            mask=transferred_masks,
        )
    )

    for name, values in prediction_errors.items():

        if values.shape != (
            REFERENCE_SAMPLE_COUNT,
        ):
            raise RuntimeError(
                f"Prediction {name} has an unexpected shape."
            )

        if not torch.isfinite(
            values
        ).all():
            raise RuntimeError(
                f"Prediction {name} contains non-finite values."
            )

    for name, values in composite_errors.items():

        if values.shape != (
            REFERENCE_SAMPLE_COUNT,
        ):
            raise RuntimeError(
                f"Composite {name} has an unexpected shape."
            )

        if not torch.isfinite(
            values
        ).all():
            raise RuntimeError(
                f"Composite {name} contains non-finite values."
            )
    for label, errors in (
        (
            "Prediction inside-mask",
            prediction_inside_errors,
        ),
        (
            "Composite inside-mask",
            composite_inside_errors,
        ),
    ):
        for name, values in errors.items():

            if values.shape != (
                REFERENCE_SAMPLE_COUNT,
            ):
                raise RuntimeError(
                    f"{label} {name} has an unexpected shape."
                )

            if not torch.isfinite(
                values
            ).all():
                raise RuntimeError(
                    f"{label} {name} contains non-finite values."
                )

    for label, errors in (
        (
            "Prediction variance",
            prediction_variance_errors,
        ),
        (
            "Composite variance",
            composite_variance_errors,
        ),
        (
            "Prediction variance inside-mask",
            prediction_variance_inside_errors,
        ),
        (
            "Composite variance inside-mask",
            composite_variance_inside_errors,
        ),
    ):
        for name, values in errors.items():

            if values.shape != (
                REFERENCE_SAMPLE_COUNT,
            ):
                raise RuntimeError(
                    f"{label} {name} has an unexpected shape."
                )

            if not torch.isfinite(
                values
            ).all():
                raise RuntimeError(
                    f"{label} {name} contains non-finite values."
                )

    summary = summarize_sample_counts(
        prediction_errors=prediction_errors,
        composite_errors=composite_errors,
        prediction_inside_errors=prediction_inside_errors,
        composite_inside_errors=composite_inside_errors,
        prediction_variance_errors=prediction_variance_errors,
        composite_variance_errors=composite_variance_errors,
        prediction_variance_inside_errors=(
            prediction_variance_inside_errors
        ),
        composite_variance_inside_errors=(
            composite_variance_inside_errors
        ),
    )

    csv_path = (
        args.output_dir
        / "posterior_convergence_summary.csv"
    )

    save_summary_csv(
        summary,
        csv_path,
    )

    figure_path = (
        args.output_dir
        / "posterior_convergence_mean_variance.png"
    )

    save_convergence_figure(
        summary=summary,
        path=figure_path,
    )

    print()

    print(
        "Inside-mask RMSE by posterior sample count"
    )

    print(
        "-" * 78
    )

    print(
        f"{'Samples':>8} "
        f"{'Prediction':>16} "
        f"{'Composite':>16}"
    )

    for row in summary:
        print(
            f"{int(row['samples']):>8d} "
            f"{row['prediction_inside_rmse']:>16.8e} "
            f"{row['composite_inside_rmse']:>16.8e}"
        )

    print()

    print(
        "Inside-mask variance RMSE by posterior sample count"
    )

    print(
        "-" * 78
    )

    print(
        f"{'Samples':>8} "
        f"{'Prediction':>16} "
        f"{'Composite':>16}"
    )

    for row in summary:
        print(
            f"{int(row['samples']):>8d} "
            f"{row['prediction_variance_inside_rmse']:>16.8e} "
            f"{row['composite_variance_inside_rmse']:>16.8e}"
        )

    print()
    print("=" * 78)
    print("BR-LoRA POSTERIOR CONVERGENCE")
    print("=" * 78)

    print(
        "Posterior realizations :",
        payload["posterior_samples"],
    )

    print(
        "Prediction shape       :",
        tuple(
            payload["prediction_samples"].shape
        ),
    )

    print(
        "Composite shape        :",
        tuple(
            payload["composite_samples"].shape
        ),
    )

    print(
        "Reference sample count :",
        REFERENCE_SAMPLE_COUNT,
    )

    print(
        "Summary CSV            :",
        csv_path,
    )

    print(
        "Convergence figure     :",
        figure_path,
    )

    print(
        "Prediction running mean : PASS"
    )

    print(
        "Composite running mean  : PASS"
    )

    print()
    print("Artifact validation: PASS")

if __name__ == "__main__":
    try:
        main()

    except (
        FileNotFoundError,
        RuntimeError,
        TypeError,
        ValueError,
    ) as exc:
        print(
            "\nBR-LoRA POSTERIOR CONVERGENCE ANALYSIS FAILED",
            file=sys.stderr,
        )

        print(
            exc,
            file=sys.stderr,
        )

        sys.exit(
            1
        )